CREATE TABLE IF NOT EXISTS players (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    game_id VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_observer BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);