[package]
authors     = { workspace = true }
description = "Shared data models for planning poker"
edition     = { workspace = true }
license     = { workspace = true }
name        = "planning_poker_models"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }