[package]
authors     = { workspace = true }
categories  = ["data-structures"]
description = "Shared data models for planning poker"
edition     = { workspace = true }
keywords    = ["models", "data", "serde", "planning-poker"]
license     = { workspace = true }
name        = "planning_poker_models"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
chrono               = { workspace = true }
moosicbox_json_utils = { workspace = true, features = ["database"] }
serde                = { workspace = true }
switchy              = { workspace = true, features = ["database"] }
uuid                 = { workspace = true }

[features]
default = []

database = []
fail-on-warnings = []

