[package]
authors     = { workspace = true }
categories  = ["database"]
description = "Database schema and migrations for planning poker"
edition     = { workspace = true }
keywords    = ["schema", "migrations", "database", "sql"]
license     = { workspace = true }
name        = "planning_poker_schema"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
planning_poker_database = { workspace = true }
switchy = { workspace = true, features = ["database", "database-schema"] }
anyhow = { workspace = true }
include_dir = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
default = ["sqlite"]
sqlite = ["planning_poker_database/sqlite"]
postgres = ["planning_poker_database/postgres"]

fail-on-warnings = []