[package]
authors     = { workspace = true }
categories  = ["database"]
description = "Database layer using switchy_database for planning poker"
edition     = { workspace = true }
keywords    = ["database", "sqlite", "postgres", "orm"]
license     = { workspace = true }
name        = "planning_poker_database"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
anyhow    = { workspace = true }
switchy   = { workspace = true, features = ["database", "database-connection"] }
thiserror = { workspace = true }
tracing   = { workspace = true }
url       = { workspace = true, optional = true }

[features]
default  = ["sqlite"]
postgres = ["dep:url", "switchy/database-connection-postgres"]
sqlite   = ["switchy/database-connection-sqlite-rusqlite"]

fail-on-warnings = []
