[package]
authors     = { workspace = true }
description = "Database layer using switchy_database for planning poker"
edition     = { workspace = true }
license     = { workspace = true }
name        = "planning_poker_database"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
switchy_database = { workspace = true }
switchy_database_connection = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true, optional = true }

[features]
default = ["sqlite"]
sqlite = ["switchy_database_connection/sqlite-rusqlite"]
postgres = ["switchy_database_connection/postgres", "dep:url"]