[package]
authors     = { workspace = true }
categories  = ["database", "web-programming"]
description = "Session management and persistence"
edition     = { workspace = true }
keywords    = ["database", "persistence", "planning-poker", "session"]
license     = { workspace = true }
name        = "planning_poker_session"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
anyhow                  = { workspace = true }
async-trait             = { workspace = true }
chrono                  = { workspace = true }
planning_poker_database = { workspace = true }
planning_poker_models   = { workspace = true }
planning_poker_schema   = { workspace = true }
switchy                 = { workspace = true, features = ["database"] }
tracing                 = { workspace = true }
uuid                    = { workspace = true }

[features]
default = ["postgres", "sqlite"]

fail-on-warnings = []

postgres = ["planning_poker_schema/postgres"]
sqlite   = ["planning_poker_schema/sqlite"]
