[package]
authors     = { workspace = true }
categories  = ["web-programming", "database"]
description = "Session management and persistence"
edition     = { workspace = true }
keywords    = ["session", "persistence", "database", "planning-poker"]
license     = { workspace = true }
name        = "planning_poker_session"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
anyhow                  = { workspace = true }
async-trait             = { workspace = true }
chrono                  = { workspace = true }
planning_poker_database = { workspace = true }
planning_poker_models   = { workspace = true }
planning_poker_schema   = { workspace = true, features = ["sqlite"] }
switchy                 = { workspace = true, features = ["database"] }
tracing                 = { workspace = true }
uuid                    = { workspace = true }

[features]
default = []

fail-on-warnings = []

