[package]
authors     = { workspace = true }
description = "Cross-platform planning poker application using HyperChad"
edition     = { workspace = true }
license     = { workspace = true }
name        = "planning_poker_app"
repository  = { workspace = true }
version     = "0.1.0"

[[bin]]
name = "planning-poker-app"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
eframe = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
hyperchad = { workspace = true, features = [
    "app",
    "renderer",
    "router",
    "state",
] }
planning_poker_models = { workspace = true }
planning_poker_ui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
switchy = { workspace = true, features = [
    "async-macros",
    "async-net",
    "async-rt-multi-thread",
    "async-sync",
    "async-time",
    "async-tokio",
    "async-util",
] }

tracing            = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["desktop"]
desktop = [
    "dep:eframe",
    "dep:egui",
    "hyperchad/renderer-egui",
    "planning_poker_ui/desktop",
]
vanilla-js = [
    "hyperchad/renderer-vanilla-js",
    "hyperchad/renderer-vanilla-js-plugin-actions",
    "hyperchad/renderer-vanilla-js-plugin-canvas",
    "hyperchad/renderer-vanilla-js-plugin-event",
    "hyperchad/renderer-vanilla-js-plugin-form",
    "hyperchad/renderer-vanilla-js-plugin-routing",
    "web",
]
web = ["hyperchad/renderer-html", "hyperchad/renderer-html-actix"]

