[package]
authors     = { workspace = true }
description = "Cross-platform planning poker application using HyperChad"
edition     = { workspace = true }
license     = { workspace = true }
name        = "planning_poker_app"
repository  = { workspace = true }
version     = "0.1.0"

[[bin]]
name = "planning-poker-app"
path = "src/main.rs"

[dependencies]
planning_poker_models = { workspace = true }
planning_poker_ui = { workspace = true }
hyperchad = { workspace = true }
hyperchad_app = { workspace = true }
hyperchad_renderer = { workspace = true }
hyperchad_renderer_egui = { workspace = true, optional = true }
hyperchad_renderer_html = { workspace = true, optional = true }
hyperchad_renderer_html_actix = { workspace = true, optional = true }
hyperchad_state = { workspace = true }
hyperchad_router = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
eframe = { workspace = true, optional = true }
egui = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["desktop"]
desktop = ["dep:hyperchad_renderer_egui", "dep:eframe", "dep:egui", "planning_poker_ui/desktop"]
web = ["dep:hyperchad_renderer_html", "dep:hyperchad_renderer_html_actix"]