[package]
authors     = { workspace = true }
categories  = ["games", "gui", "web-programming"]
description = "Cross-platform planning poker application using HyperChad"
edition     = { workspace = true }
keywords    = ["agile", "estimation", "gui", "planning-poker", "scrum"]
license     = { workspace = true }
name        = "planning_poker_app"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[[bin]]
name = "planning-poker-app"
path = "src/main.rs"

[[bin]]
name              = "planning-poker-app-lambda"
path              = "src/lambda.rs"
required-features = ["lambda", "vanilla-js"]

[dependencies]
bytes = { workspace = true }
chrono = { workspace = true }
hyperchad = { workspace = true, features = [
    "actions",
    "actions-logic",
    "app",
    "color",
    "renderer",
    "router",
    "router-form",
    "router-serde",
    "state",
    "template",
    "transformer",
    "json",
] }
planning_poker_config = { workspace = true }
planning_poker_models = { workspace = true }
planning_poker_session = { workspace = true }
planning_poker_state = { workspace = true }
planning_poker_ui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
switchy = { workspace = true, features = [
    "async-macros",
    "async-net",
    "async-rt-multi-thread",
    "async-sync",
    "async-time",
    "async-tokio",
    "async-util",
] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["desktop"]
desktop = ["hyperchad/renderer-egui"]
vanilla-js = [
    "hyperchad/renderer-vanilla-js",
    "hyperchad/renderer-vanilla-js-plugin-actions",
    "hyperchad/renderer-vanilla-js-plugin-event",
    "hyperchad/renderer-vanilla-js-plugin-form",
    "hyperchad/renderer-vanilla-js-plugin-idiomorph",
    "hyperchad/renderer-vanilla-js-plugin-nav",
    "hyperchad/renderer-vanilla-js-plugin-routing",
    "hyperchad/renderer-vanilla-js-plugin-sse",
    "hyperchad/renderer-vanilla-js-plugin-uuid",
]

postgres = ["planning_poker_session/postgres", "planning_poker_state/postgres"]
sqlite   = ["planning_poker_session/sqlite", "planning_poker_state/sqlite"]

_sse = [
    "hyperchad/renderer-html-sse",
    "hyperchad/renderer-vanilla-js-plugin-sse",
]

actix = ["_sse", "hyperchad/renderer-html-actix"]
lambda = [
    "_sse",
    "hyperchad/renderer-html-cdn",
    "hyperchad/renderer-html-lambda",
]

assets        = ["hyperchad/renderer-assets"]
insecure      = ["hyperchad/renderer-vanilla-js-plugin-uuid-insecure"]
static-routes = ["hyperchad/router-static-routes"]

dev = ["assets", "insecure", "static-routes"]

fail-on-warnings = []
