[package]
authors     = { workspace = true }
description = "Planning poker WebSocket server"
edition     = { workspace = true }
license     = { workspace = true }
name        = "planning_poker_server"
repository  = { workspace = true }
version     = "0.1.0"

[[bin]]
name = "planning-poker-server"
path = "src/main.rs"

[dependencies]
planning_poker_models = { workspace = true }
planning_poker_session = { workspace = true }
planning_poker_websocket = { workspace = true }
planning_poker_api = { workspace = true }
planning_poker_config = { workspace = true }
planning_poker_database = { workspace = true }
actix-web = { workspace = true }
actix-ws = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }