[package]
authors     = { workspace = true }
categories  = ["gui", "web-programming"]
description = "Shared UI components for planning poker"
edition     = { workspace = true }
keywords    = ["ui", "components", "gui", "web", "planning-poker"]
license     = { workspace = true }
name        = "planning_poker_ui"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
anyhow = { workspace = true }
hyperchad = { workspace = true, features = [
    "app",
    "color",
    "renderer",
    "router",
    "state",
    "template",
    "transformer",
] }
planning_poker_models = { workspace = true }
planning_poker_poker = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[features]
default = []

fail-on-warnings = []

