[package]
authors     = { workspace = true }
categories  = ["config", "development-tools"]
description = "Configuration management for planning poker"
edition     = { workspace = true }
keywords    = ["config", "settings", "toml"]
license     = { workspace = true }
name        = "planning_poker_config"
readme      = "../../README.md"
repository  = { workspace = true }
version     = "0.1.0"

[dependencies]
anyhow    = { workspace = true }
serde     = { workspace = true }
thiserror = { workspace = true }
toml      = { workspace = true }

[features]
default = []

fail-on-warnings = []
