name: Publish Crates

on:
    workflow_dispatch:
        inputs:
            dry_run:
                description: 'Perform a dry run (do not actually publish)'
                required: false
                default: 'true'
                type: boolean

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y pkg-config libssl-dev libsqlite3-dev

            - name: Install cargo-workspaces
              run: cargo install cargo-workspaces

            - name: Dry run publish
              if: ${{ github.event.inputs.dry_run == 'true' }}
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
              run: |
                  cargo workspaces publish --dry-run --publish-as-is

            - name: Publish crates
              if: ${{ github.event.inputs.dry_run == 'false' }}
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
              run: |
                  cargo workspaces publish --publish-as-is